-- countries
CREATE TABLE countries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  name_local text,
  iso_code text NOT NULL,
  icon text NOT NULL,
  structure text NOT NULL,
  continent text NOT NULL,
  timezone text,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  rest jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_countries_iso_code ON countries (iso_code);
CREATE INDEX idx_countries_is_deleted ON countries (is_deleted) WHERE is_deleted = false;

-- admin_divisions
CREATE TABLE admin_divisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id bigint NOT NULL REFERENCES countries (id) ON DELETE RESTRICT,
  parent_id bigint REFERENCES admin_divisions (id) ON DELETE RESTRICT,
  name text NOT NULL,
  name_local text,
  code text,
  type text NOT NULL,
  level integer NOT NULL,
  path text NOT NULL,
  timezone text,
  rest jsonb,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_admin_divisions_country_level ON admin_divisions (country_id, level);
CREATE INDEX idx_admin_divisions_country_parent ON admin_divisions (country_id, parent_id);
CREATE INDEX idx_admin_divisions_path_prefix ON admin_divisions (path text_pattern_ops);
CREATE INDEX idx_admin_divisions_is_deleted ON admin_divisions (is_deleted) WHERE is_deleted = false;

-- optional: updated_at trigger for countries
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER countries_updated_at
  BEFORE UPDATE ON countries
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

CREATE TRIGGER admin_divisions_updated_at
  BEFORE UPDATE ON admin_divisions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();





-- search
create or replace function search_admin_divisions(
  search text,
  lvl int,
  cid bigint,
  lim int
)
returns setof admin_divisions
language sql
stable
as $$
  select *
  from admin_divisions
  where
    is_deleted = false
    and level = lvl
    and country_id = cid
    and (
      name ilike '%' || search || '%'
      or path ilike '%' || search || '%'
    )
  order by path
  limit lim;
$$;


create or replace function search_admin_divisions_with_parentid(
  search text,
  lvl int,
  cid bigint,
  parent bigint,
  lim int
)
returns setof admin_divisions
language sql
stable
as $$
  select *
  from admin_divisions
  where
    is_deleted = false
    and level = lvl
    and country_id = cid
    and parent_id = parent
    and (
      name ilike '%' || search || '%'
      or path ilike '%' || search || '%'
    )
  order by path
  limit lim;
$$;
